// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVZnfCl3HLaR2ym-b74SNTIh673LjWVA',
    appId: '1:970922395116:web:274a2cad23873d8964ecc9',
    messagingSenderId: '970922395116',
    projectId: 'clot-a86ea',
    authDomain: 'clot-a86ea.firebaseapp.com',
    storageBucket: 'clot-a86ea.firebasestorage.app',
    measurementId: 'G-PZMGF60NM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfios7KSjy1RsHsxnWwrpRyyQkLtsKnnE',
    appId: '1:970922395116:android:17e0c0bdba2e9ab864ecc9',
    messagingSenderId: '970922395116',
    projectId: 'clot-a86ea',
    storageBucket: 'clot-a86ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdr_WA4ZPLEZ6fZqxiLCf4mPhxk-b8c7E',
    appId: '1:970922395116:ios:57ae0e80e9fd37e264ecc9',
    messagingSenderId: '970922395116',
    projectId: 'clot-a86ea',
    storageBucket: 'clot-a86ea.firebasestorage.app',
    iosBundleId: 'com.example.clot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdr_WA4ZPLEZ6fZqxiLCf4mPhxk-b8c7E',
    appId: '1:970922395116:ios:57ae0e80e9fd37e264ecc9',
    messagingSenderId: '970922395116',
    projectId: 'clot-a86ea',
    storageBucket: 'clot-a86ea.firebasestorage.app',
    iosBundleId: 'com.example.clot',
  );
}
